version: '3.8'

services:
  taxcalculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sqlite-data:/app/Data
    networks:
      - taxnet

  # Optional: SQLite Admin UI (Web interface)
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - sqlite-data:/data
    command: /data/TaxCalculator.db
    networks:
      - taxnet

volumes:
  sqlite-data:

networks:
  taxnet:
