version: '3.8'

services:
  taxcalculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sqlite-data:/app/Data
    networks:
      - taxnet

  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - sqlite-data:/data
    command: /data/TaxCalculator.db
    networks:
      - taxnet

  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  sqlite-data:

networks:
  taxnet:
